/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/boxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Boxes */
        get: operations["list_boxes_boxes_get"];
        put?: never;
        /** Create Box */
        post: operations["create_box_boxes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boxes/{box_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Box */
        patch: operations["update_box_boxes__box_id__patch"];
        trace?: never;
    };
    "/boxes/{box_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Box */
        post: operations["archive_box_boxes__box_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/car-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Car Types */
        get: operations["list_car_types_car_types_get"];
        put?: never;
        /** Create Car Type */
        post: operations["create_car_type_car_types_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/car-types/{car_type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Car Type */
        patch: operations["update_car_type_car_types__car_type_id__patch"];
        trace?: never;
    };
    "/car-types/{car_type_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Car Type */
        post: operations["archive_car_type_car_types__car_type_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Cars */
        get: operations["search_cars_cars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Clients */
        get: operations["search_clients_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{client_id}/cars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Client Cars */
        get: operations["list_client_cars_clients__client_id__cars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by deploys and uptime checks.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Order */
        post: operations["cancel_order_orders__order_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Order */
        post: operations["close_order_orders__order_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Payments */
        get: operations["list_payments_orders__order_id__payments_get"];
        put?: never;
        /** Record Payment */
        post: operations["record_payment_orders__order_id__payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/package-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Package Prices */
        get: operations["list_package_prices_package_prices_get"];
        /** Upsert Package Price */
        put: operations["upsert_package_price_package_prices_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packages */
        get: operations["list_packages_packages_get"];
        put?: never;
        /** Create Package */
        post: operations["create_package_packages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Package */
        patch: operations["update_package_packages__package_id__patch"];
        trace?: never;
    };
    "/packages/{package_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Package */
        post: operations["archive_package_packages__package_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Package Services */
        put: operations["set_package_services_packages__package_id__services_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Service Prices */
        get: operations["list_service_prices_service_prices_get"];
        /** Upsert Service Price */
        put: operations["upsert_service_price_service_prices_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Services */
        get: operations["list_services_services_get"];
        put?: never;
        /** Create Service */
        post: operations["create_service_services_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{service_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Service */
        patch: operations["update_service_services__service_id__patch"];
        trace?: never;
    };
    "/services/{service_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Service */
        post: operations["archive_service_services__service_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Shift */
        post: operations["close_shift_shifts_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Shift */
        get: operations["current_shift_shifts_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/current/cash-movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Cash Movement */
        post: operations["record_cash_movement_shifts_current_cash_movements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Shift */
        post: operations["open_shift_shifts_open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Staff
         * @description Users assignable as washers at the active car wash: members scoped to this
         *     car wash plus org-level members (owner/org_admin who can also work the floor).
         */
        get: operations["list_staff_staff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BoxCreate */
        BoxCreate: {
            /** Name */
            name: string;
            /**
             * Sort
             * @default 0
             */
            sort: number;
        };
        /** BoxOut */
        BoxOut: {
            /** Active Order Id */
            active_order_id: string | null;
            /**
             * Car Wash Id
             * Format: uuid
             */
            car_wash_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Sort */
            sort: number;
            status: components["schemas"]["BoxStatus"];
        };
        /**
         * BoxStatus
         * @enum {string}
         */
        BoxStatus: "free" | "busy";
        /** BoxUpdate */
        BoxUpdate: {
            /** Name */
            name?: string | null;
            /** Sort */
            sort?: number | null;
        };
        /** CarOut */
        CarOut: {
            /** Brand */
            brand: string | null;
            /**
             * Car Type Id
             * Format: uuid
             */
            car_type_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Model */
            model: string | null;
            /** Plate */
            plate: string;
        };
        /** CarTypeCreate */
        CarTypeCreate: {
            /** Name */
            name: string;
            /**
             * Sort
             * @default 0
             */
            sort: number;
        };
        /** CarTypeOut */
        CarTypeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Sort */
            sort: number;
        };
        /** CarTypeUpdate */
        CarTypeUpdate: {
            /** Name */
            name?: string | null;
            /** Sort */
            sort?: number | null;
        };
        /** CarWashOut */
        CarWashOut: {
            /** Currency */
            currency: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
        };
        /** CashMovementCreate */
        CashMovementCreate: {
            /** Amount Minor */
            amount_minor: number;
            /** Payee User Id */
            payee_user_id?: string | null;
            /** Reason */
            reason?: string | null;
            type: components["schemas"]["CashMovementType"];
        };
        /** CashMovementOut */
        CashMovementOut: {
            /** Amount Minor */
            amount_minor: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Payee User Id */
            payee_user_id: string | null;
            /** Reason */
            reason: string | null;
            /**
             * Shift Id
             * Format: uuid
             */
            shift_id: string;
            type: components["schemas"]["CashMovementType"];
        };
        /**
         * CashMovementType
         * @enum {string}
         */
        CashMovementType: "expense" | "payout" | "collection" | "deposit";
        /**
         * ClientKind
         * @enum {string}
         */
        ClientKind: "walkin" | "regular" | "corporate";
        /** ClientOut */
        ClientOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["ClientKind"];
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
        };
        /** DiscountIn */
        DiscountIn: {
            /** Amount Minor */
            amount_minor: number;
            /** @default manual */
            type: components["schemas"]["DiscountType"];
        };
        /**
         * DiscountType
         * @enum {string}
         */
        DiscountType: "none" | "manual" | "loyalty" | "promo" | "subscription";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntakeIn
         * @description Registered intake (name/phone present → upsert) or walk-in (plate only).
         */
        IntakeIn: {
            /** Brand */
            brand?: string | null;
            /** @default walkin */
            client_kind: components["schemas"]["ClientKind"];
            /** Client Name */
            client_name?: string | null;
            /** Client Phone */
            client_phone?: string | null;
            /** Model */
            model?: string | null;
            /** Plate */
            plate?: string | null;
        };
        /** MeResponse */
        MeResponse: {
            /** Accessible Car Washes */
            accessible_car_washes: components["schemas"]["CarWashOut"][];
            /** Active Car Wash Id */
            active_car_wash_id: string | null;
            /** Capabilities */
            capabilities: string[];
            organization: components["schemas"]["OrganizationOut"];
            role: components["schemas"]["MembershipRole"];
            user: components["schemas"]["ProfileOut"];
        };
        /**
         * MembershipRole
         * @enum {string}
         */
        MembershipRole: "owner" | "org_admin" | "manager" | "washer";
        /** OrderCreate */
        OrderCreate: {
            /**
             * Box Id
             * Format: uuid
             */
            box_id: string;
            /**
             * Car Type Id
             * Format: uuid
             */
            car_type_id: string;
            /** Client Car Id */
            client_car_id?: string | null;
            discount?: components["schemas"]["DiscountIn"] | null;
            intake?: components["schemas"]["IntakeIn"] | null;
            /** Package Id */
            package_id?: string | null;
            /**
             * Services
             * @default []
             */
            services: components["schemas"]["OrderServiceIn"][];
            /**
             * Washer User Ids
             * @default []
             */
            washer_user_ids: string[];
        };
        /** OrderDetailOut */
        OrderDetailOut: {
            /** Balance Minor */
            balance_minor: number;
            /**
             * Box Id
             * Format: uuid
             */
            box_id: string;
            /** Car Brand */
            car_brand: string | null;
            /** Car Model */
            car_model: string | null;
            /**
             * Car Type Id
             * Format: uuid
             */
            car_type_id: string;
            /**
             * Car Wash Id
             * Format: uuid
             */
            car_wash_id: string;
            /** Client Car Id */
            client_car_id: string | null;
            /** Client Name */
            client_name: string | null;
            /** Client Phone */
            client_phone: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /** Currency */
            currency: string;
            /** Discount Amount Minor */
            discount_amount_minor: number;
            discount_type: components["schemas"]["DiscountType"];
            /** Finished At */
            finished_at: string | null;
            /** Finished By */
            finished_by: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /** Package Id */
            package_id: string | null;
            /** Paid Total Minor */
            paid_total_minor: number;
            payment_status: components["schemas"]["OrderPaymentStatus"];
            /** Payments */
            payments: components["schemas"]["PaymentOut"][];
            /** Plate */
            plate: string | null;
            /** Services */
            services: components["schemas"]["OrderServiceOut"][];
            /**
             * Shift Id
             * Format: uuid
             */
            shift_id: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["OrderStatus"];
            /** Subtotal Minor */
            subtotal_minor: number;
            /** Total Minor */
            total_minor: number;
            /** Washers */
            washers: components["schemas"]["OrderWasherOut"][];
        };
        /** OrderOut */
        OrderOut: {
            /**
             * Box Id
             * Format: uuid
             */
            box_id: string;
            /** Car Brand */
            car_brand: string | null;
            /** Car Model */
            car_model: string | null;
            /**
             * Car Type Id
             * Format: uuid
             */
            car_type_id: string;
            /**
             * Car Wash Id
             * Format: uuid
             */
            car_wash_id: string;
            /** Client Car Id */
            client_car_id: string | null;
            /** Client Name */
            client_name: string | null;
            /** Client Phone */
            client_phone: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /** Currency */
            currency: string;
            /** Discount Amount Minor */
            discount_amount_minor: number;
            discount_type: components["schemas"]["DiscountType"];
            /** Finished At */
            finished_at: string | null;
            /** Finished By */
            finished_by: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /** Package Id */
            package_id: string | null;
            payment_status: components["schemas"]["OrderPaymentStatus"];
            /** Plate */
            plate: string | null;
            /**
             * Shift Id
             * Format: uuid
             */
            shift_id: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["OrderStatus"];
            /** Subtotal Minor */
            subtotal_minor: number;
            /** Total Minor */
            total_minor: number;
            /** Washers */
            washers: components["schemas"]["OrderWasherBrief"][];
        };
        /** OrderPage */
        OrderPage: {
            /** Items */
            items: components["schemas"]["OrderOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * OrderPaymentStatus
         * @enum {string}
         */
        OrderPaymentStatus: "unpaid" | "partial" | "paid" | "credit" | "refunded";
        /** OrderServiceIn */
        OrderServiceIn: {
            /**
             * Qty
             * @default 1
             */
            qty: number;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
        };
        /** OrderServiceOut */
        OrderServiceOut: {
            /** Qty */
            qty: number;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /** Unit Amount Minor */
            unit_amount_minor: number;
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "queued" | "in_progress" | "done" | "cancelled";
        /**
         * OrderWasherBrief
         * @description A washer assigned to an order, with the display name from ``profiles``.
         */
        OrderWasherBrief: {
            /** Name */
            name: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** OrderWasherOut */
        OrderWasherOut: {
            /** Earned Amount Minor */
            earned_amount_minor: number;
            /** Name */
            name: string | null;
            /** Share Bps */
            share_bps: number;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** OrganizationOut */
        OrganizationOut: {
            /** Default Currency */
            default_currency: string;
            /** Default Locale */
            default_locale: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** PackageCreate */
        PackageCreate: {
            /** Name */
            name: string;
        };
        /** PackageOut */
        PackageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Service Ids */
            service_ids: string[];
        };
        /** PackagePriceOut */
        PackagePriceOut: {
            /** Amount Minor */
            amount_minor: number;
            /**
             * Car Type Id
             * Format: uuid
             */
            car_type_id: string;
            /**
             * Car Wash Id
             * Format: uuid
             */
            car_wash_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Package Id
             * Format: uuid
             */
            package_id: string;
        };
        /** PackagePriceUpsert */
        PackagePriceUpsert: {
            /** Amount Minor */
            amount_minor: number;
            /**
             * Car Type Id
             * Format: uuid
             */
            car_type_id: string;
            /**
             * Package Id
             * Format: uuid
             */
            package_id: string;
        };
        /** PackageServicesUpdate */
        PackageServicesUpdate: {
            /** Service Ids */
            service_ids: string[];
        };
        /** PackageUpdate */
        PackageUpdate: {
            /** Name */
            name?: string | null;
        };
        /** PaymentCreate */
        PaymentCreate: {
            /** Amount Minor */
            amount_minor: number;
            /** @default payment */
            kind: components["schemas"]["PaymentKind"];
            method: components["schemas"]["PaymentMethod"];
        };
        /**
         * PaymentKind
         * @enum {string}
         */
        PaymentKind: "payment" | "refund";
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "cash" | "card" | "transfer" | "bonus";
        /** PaymentOut */
        PaymentOut: {
            /** Amount Minor */
            amount_minor: number;
            /** Currency */
            currency: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["PaymentKind"];
            method: components["schemas"]["PaymentMethod"];
            /**
             * Paid At
             * Format: date-time
             */
            paid_at: string;
            /** Received By */
            received_by: string | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Full Name */
            full_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Locale */
            locale: string | null;
        };
        /** ServiceCreate */
        ServiceCreate: {
            /** Name */
            name: string;
        };
        /** ServiceOut */
        ServiceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
        };
        /** ServicePriceOut */
        ServicePriceOut: {
            /** Amount Minor */
            amount_minor: number;
            /**
             * Car Type Id
             * Format: uuid
             */
            car_type_id: string;
            /**
             * Car Wash Id
             * Format: uuid
             */
            car_wash_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
        };
        /** ServicePriceUpsert */
        ServicePriceUpsert: {
            /** Amount Minor */
            amount_minor: number;
            /**
             * Car Type Id
             * Format: uuid
             */
            car_type_id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
        };
        /** ServiceUpdate */
        ServiceUpdate: {
            /** Name */
            name?: string | null;
        };
        /** ShiftClose */
        ShiftClose: {
            /** Counted Cash Minor */
            counted_cash_minor: number;
        };
        /** ShiftCloseOut */
        ShiftCloseOut: {
            /** Counted Minor */
            counted_minor: number;
            /** Expected Minor */
            expected_minor: number;
            shift: components["schemas"]["ShiftOut"];
            /** Variance Minor */
            variance_minor: number;
        };
        /** ShiftOpen */
        ShiftOpen: {
            /** Opening Float Minor */
            opening_float_minor: number;
        };
        /** ShiftOut */
        ShiftOut: {
            /**
             * Car Wash Id
             * Format: uuid
             */
            car_wash_id: string;
            /** Closed At */
            closed_at: string | null;
            /** Closed By */
            closed_by: string | null;
            /** Closing Expected Minor */
            closing_expected_minor: number | null;
            /** Counted Cash Minor */
            counted_cash_minor: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Opened By
             * Format: uuid
             */
            opened_by: string;
            /** Opening Float Minor */
            opening_float_minor: number;
        };
        /**
         * StaffOut
         * @description A user assignable as a washer at the active car wash.
         */
        StaffOut: {
            /** Name */
            name: string | null;
            role: components["schemas"]["MembershipRole"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_boxes_boxes_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoxOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_box_boxes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoxCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoxOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_box_boxes__box_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                box_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoxUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoxOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_box_boxes__box_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                box_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoxOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_car_types_car_types_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarTypeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_car_type_car_types_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarTypeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarTypeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_car_type_car_types__car_type_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                car_type_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarTypeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarTypeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_car_type_car_types__car_type_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                car_type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarTypeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_cars_cars_get: {
        parameters: {
            query: {
                plate: string;
            };
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_clients_clients_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_client_cars_clients__client_id__cars_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_orders_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["OrderStatus"] | null;
                box_id?: string | null;
                created_from?: string | null;
                created_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_orders_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_orders__order_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_order_orders__order_id__close_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_payments_orders__order_id__payments_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_payment_orders__order_id__payments_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_package_prices_package_prices_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackagePriceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_package_price_package_prices_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackagePriceUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackagePriceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_packages_packages_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_package_packages_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_package_packages__package_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_package_packages__package_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_package_services_packages__package_id__services_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageServicesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_service_prices_service_prices_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicePriceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_service_price_service_prices_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicePriceUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicePriceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_services_services_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_service_services_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_service_services__service_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_service_services__service_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_shift_shifts_close_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftClose"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftCloseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_shift_shifts_current_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_cash_movement_shifts_current_cash_movements_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashMovementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashMovementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_shift_shifts_open_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftOpen"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_staff_staff_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Car-Wash-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
