"""pricing

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-16 18:28:07.536014
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "car_types",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sort", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_car_types_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_car_types")),
    )
    op.create_index(
        op.f("ix_car_types_organization_id"), "car_types", ["organization_id"], unique=False
    )
    op.create_table(
        "packages",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_packages_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
    )
    op.create_index(
        op.f("ix_packages_organization_id"), "packages", ["organization_id"], unique=False
    )
    op.create_table(
        "services",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_services_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_index(
        op.f("ix_services_organization_id"), "services", ["organization_id"], unique=False
    )
    op.create_table(
        "package_prices",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("car_wash_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("car_type_id", sa.Uuid(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["car_type_id"],
            ["car_types.id"],
            name=op.f("fk_package_prices_car_type_id_car_types"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["car_wash_id"],
            ["car_washes.id"],
            name=op.f("fk_package_prices_car_wash_id_car_washes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_package_prices_package_id_packages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_prices")),
        sa.UniqueConstraint(
            "car_wash_id", "package_id", "car_type_id", name=op.f("uq_package_prices_car_wash_id")
        ),
    )
    op.create_index(
        op.f("ix_package_prices_car_type_id"), "package_prices", ["car_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_package_prices_car_wash_id"), "package_prices", ["car_wash_id"], unique=False
    )
    op.create_index(
        op.f("ix_package_prices_package_id"), "package_prices", ["package_id"], unique=False
    )
    op.create_table(
        "package_services",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_package_services_package_id_packages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_package_services_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_services")),
        sa.UniqueConstraint(
            "package_id", "service_id", name=op.f("uq_package_services_package_id")
        ),
    )
    op.create_index(
        op.f("ix_package_services_package_id"), "package_services", ["package_id"], unique=False
    )
    op.create_index(
        op.f("ix_package_services_service_id"), "package_services", ["service_id"], unique=False
    )
    op.create_table(
        "service_prices",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("car_wash_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("car_type_id", sa.Uuid(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["car_type_id"],
            ["car_types.id"],
            name=op.f("fk_service_prices_car_type_id_car_types"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["car_wash_id"],
            ["car_washes.id"],
            name=op.f("fk_service_prices_car_wash_id_car_washes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_service_prices_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_prices")),
        sa.UniqueConstraint(
            "car_wash_id", "service_id", "car_type_id", name=op.f("uq_service_prices_car_wash_id")
        ),
    )
    op.create_index(
        op.f("ix_service_prices_car_type_id"), "service_prices", ["car_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_prices_car_wash_id"), "service_prices", ["car_wash_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_prices_service_id"), "service_prices", ["service_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_prices_service_id"), table_name="service_prices")
    op.drop_index(op.f("ix_service_prices_car_wash_id"), table_name="service_prices")
    op.drop_index(op.f("ix_service_prices_car_type_id"), table_name="service_prices")
    op.drop_table("service_prices")
    op.drop_index(op.f("ix_package_services_service_id"), table_name="package_services")
    op.drop_index(op.f("ix_package_services_package_id"), table_name="package_services")
    op.drop_table("package_services")
    op.drop_index(op.f("ix_package_prices_package_id"), table_name="package_prices")
    op.drop_index(op.f("ix_package_prices_car_wash_id"), table_name="package_prices")
    op.drop_index(op.f("ix_package_prices_car_type_id"), table_name="package_prices")
    op.drop_table("package_prices")
    op.drop_index(op.f("ix_services_organization_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_packages_organization_id"), table_name="packages")
    op.drop_table("packages")
    op.drop_index(op.f("ix_car_types_organization_id"), table_name="car_types")
    op.drop_table("car_types")
    # ### end Alembic commands ###
