"""orders

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-16 18:28:44.660242
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_clients_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_index(
        op.f("ix_clients_organization_id"), "clients", ["organization_id"], unique=False
    )
    op.create_table(
        "boxes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("car_wash_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("free", "busy", name="box_status"),
            server_default="free",
            nullable=False,
        ),
        sa.Column("active_order_id", sa.Uuid(), nullable=True),
        sa.Column("sort", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["car_wash_id"],
            ["car_washes.id"],
            name=op.f("fk_boxes_car_wash_id_car_washes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boxes")),
    )
    op.create_index(op.f("ix_boxes_car_wash_id"), "boxes", ["car_wash_id"], unique=False)
    op.create_table(
        "cars",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("plate", sa.Text(), nullable=False),
        sa.Column("car_type_id", sa.Uuid(), nullable=False),
        sa.Column("brand", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["car_type_id"],
            ["car_types.id"],
            name=op.f("fk_cars_car_type_id_car_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cars")),
    )
    op.create_index(op.f("ix_cars_car_type_id"), "cars", ["car_type_id"], unique=False)
    op.create_table(
        "shifts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("car_wash_id", sa.Uuid(), nullable=False),
        sa.Column("opened_by", sa.Uuid(), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["car_wash_id"],
            ["car_washes.id"],
            name=op.f("fk_shifts_car_wash_id_car_washes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by"],
            ["auth.users.id"],
            name=op.f("fk_shifts_opened_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shifts")),
    )
    op.create_index(op.f("ix_shifts_car_wash_id"), "shifts", ["car_wash_id"], unique=False)
    op.create_index(op.f("ix_shifts_opened_by"), "shifts", ["opened_by"], unique=False)
    op.create_table(
        "client_cars",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("car_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["car_id"], ["cars.id"], name=op.f("fk_client_cars_car_id_cars"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_cars_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_cars")),
    )
    op.create_index(op.f("ix_client_cars_car_id"), "client_cars", ["car_id"], unique=False)
    op.create_index(op.f("ix_client_cars_client_id"), "client_cars", ["client_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("car_wash_id", sa.Uuid(), nullable=False),
        sa.Column("box_id", sa.Uuid(), nullable=False),
        sa.Column("shift_id", sa.Uuid(), nullable=False),
        sa.Column("client_car_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "in_progress", "done", "cancelled", name="order_status"),
            nullable=False,
        ),
        sa.Column("price_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("discount_pct", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["box_id"], ["boxes.id"], name=op.f("fk_orders_box_id_boxes"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["car_wash_id"],
            ["car_washes.id"],
            name=op.f("fk_orders_car_wash_id_car_washes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["client_car_id"],
            ["client_cars.id"],
            name=op.f("fk_orders_client_car_id_client_cars"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["auth.users.id"],
            name=op.f("fk_orders_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_orders_package_id_packages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["shifts.id"], name=op.f("fk_orders_shift_id_shifts"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_box_id"), "orders", ["box_id"], unique=False)
    op.create_index(op.f("ix_orders_car_wash_id"), "orders", ["car_wash_id"], unique=False)
    op.create_index(
        "ix_orders_car_wash_id_status", "orders", ["car_wash_id", "status"], unique=False
    )
    op.create_index(op.f("ix_orders_client_car_id"), "orders", ["client_car_id"], unique=False)
    op.create_index(op.f("ix_orders_created_by"), "orders", ["created_by"], unique=False)
    op.create_index(op.f("ix_orders_package_id"), "orders", ["package_id"], unique=False)
    op.create_index(op.f("ix_orders_shift_id"), "orders", ["shift_id"], unique=False)
    op.create_table(
        "order_services",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("unit_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("qty", sa.SmallInteger(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_services_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_order_services_service_id_services"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_services")),
    )
    op.create_index(
        op.f("ix_order_services_order_id"), "order_services", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_services_service_id"), "order_services", ["service_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_services_service_id"), table_name="order_services")
    op.drop_index(op.f("ix_order_services_order_id"), table_name="order_services")
    op.drop_table("order_services")
    op.drop_index(op.f("ix_orders_shift_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_package_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_by"), table_name="orders")
    op.drop_index(op.f("ix_orders_client_car_id"), table_name="orders")
    op.drop_index("ix_orders_car_wash_id_status", table_name="orders")
    op.drop_index(op.f("ix_orders_car_wash_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_box_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_client_cars_client_id"), table_name="client_cars")
    op.drop_index(op.f("ix_client_cars_car_id"), table_name="client_cars")
    op.drop_table("client_cars")
    op.drop_index(op.f("ix_shifts_opened_by"), table_name="shifts")
    op.drop_index(op.f("ix_shifts_car_wash_id"), table_name="shifts")
    op.drop_table("shifts")
    op.drop_index(op.f("ix_cars_car_type_id"), table_name="cars")
    op.drop_table("cars")
    op.drop_index(op.f("ix_boxes_car_wash_id"), table_name="boxes")
    op.drop_table("boxes")
    op.drop_index(op.f("ix_clients_organization_id"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS order_status")
    op.execute("DROP TYPE IF EXISTS box_status")
